version: '3'

services:
  registry:
    image: registry:latest
    ports:
    - "718:718"
    environment:
      REGISTRY_HTTP_ADDR=0.0.0.0:718
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/registry.password
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /registry-data
    volumes:
    - ./auth:/auth
    - ./registry-data:/registry-data
  docker-registry-ui:
    container_name: docker-registry-ui
    image: konradkleine/docker-registry-frontend:v2
    ports:
    - 719:443
    environment:
      ENV_DOCKER_REGISTRY_PORT: 718
