---
version: '3'

services:
    docker-registry:
        container_name: hub.kubernetesway.in
        image: registry
        ports:
            - 443:443
        environment:
          REGISTRY_AUTH: htpasswd
          REGISTRY_AUTH_HTPASSWD_REALM: Registry
          REGISTRY_AUTH_HTPASSWD_PATH: /auth/registry.password
          REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /registry-data
        volumes:
          - ./auth:/auth
          - ./registry-data:/registry-data
        restart: always
    docker-registry-ui:
        container_name: docker-registry-ui
        image: konradkleine/docker-registry-frontend:v2
        ports:
            - 8443:443
        environment:
            ENV_DOCKER_REGISTRY_HOST: hub.kubernetesway.in
            ENV_DOCKER_REGISTRY_PORT: 443
