version: '2.0'
services:
  ui:
    image: joxit/docker-registry-ui:latest
    ports:
      - 719:80
    environment:
      - REGISTRY_TITLE=Docker Registry
      - REGISTRY_URL=http://localhost:718
      - SINGLE_REGISTRY=true