name: Copy commit files

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/*.yml'

jobs:
  copy-commit-files:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Copy Files to Commits Directory
        if: github.event.actor != 'github-actions[bot]'
        run: |
          if [ -d ".commits/" ]; then
            rm -r .commits/
          fi
          mkdir -p ".commits/${{ github.sha }}"
          find . -maxdepth 1 -type f -not -path '*/\.*' -exec cp {} ".commits/${{ github.sha }}/" \;
          git add ".commits/${{ github.sha }}/"

      - name: Commit & Push changes
        uses: Andro999b/push@v1.3
        if: github.event.actor != 'github-actions[bot]'
        with:
          github_token: ${{ secrets.PAT }}
          message: "Add files from commit ${{ github.sha }} to .commits directory"
          branch: "main"
