name: Copy commit files

on:
  push:

jobs:
  copy-commit-files:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Git
        run: echo "${{ secrets.PAT }}" | gh auth login --with-token

      - name: Copy Files to Commits Directory
        run: |
          mkdir -p ".commits/${{ github.sha }}"
          find . -maxdepth 1 -type f -not -path '*/\.*' -exec cp {} ".commits/${{ github.sha }}/" \;
          git add ".commits/${{ github.sha }}/"

      - name: List Folder
        run: |
          ls ".commits/${{ github.sha }}"

      - name: Commit Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git commit -m "Add files from commit ${{ github.sha }} to .commits directory"

      - name: Push Changes
        run: |
          git push
          
      - name: Reset to last Commit
        run: |
          git fetch
          git reset --hard HEAD~1
          git clean -f

      - name: List Last Commit Changes
        run: |
          git log -n 1 --pretty=format:"%h: %s" HEAD

      - name: Verify Commit in Branch
        run: |
          git branch --show-current
          git rev-parse --short HEAD