name: Get Commit Hash

on:
  push:

jobs:
  get-commit-hash:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Copy Files to Commits Directory
        run: |
          commit_hash= ${{ github.sha }}
          mkdir -p ".commits/$commit_hash"
          find . -maxdepth 1 -type f -not -path '*/\.*' -exec cp {} ".commits/$commit_hash/" \;
          git add ".commits/$commit_hash/"

      - name: Commit Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git commit -m "Add files from commit $commit_hash to .commits directory"