name: Get Commit Hash

on:
  push:

jobs:
  get-commit-hash:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Copy Files to Commits Directory
        run: |
          mkdir -p ".commits/${{ github.sha }}"
          find . -maxdepth 1 -type f -not -path '*/\.*' -exec cp {} ".commits/${{ github.sha }}/" \;
          git add ".commits/${{ github.sha }}/"

      - name: Commit Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git commit -m "Add files from commit ${{ github.sha }} to .commits directory"

      - name: Push Changes
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}

  - name: Verify Commit in Branch
        run: git branch --show-current